/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/assignments/': RouteRecordInfo<'/assignments/', '/assignments', Record<never, never>, Record<never, never>>,
    '/assignments/[id]': RouteRecordInfo<'/assignments/[id]', '/assignments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/classes/': RouteRecordInfo<'/classes/', '/classes', Record<never, never>, Record<never, never>>,
    '/essays/': RouteRecordInfo<'/essays/', '/essays', Record<never, never>, Record<never, never>>,
    '/essays/[id]': RouteRecordInfo<'/essays/[id]', '/essays/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/essays/upload': RouteRecordInfo<'/essays/upload', '/essays/upload', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/students/': RouteRecordInfo<'/students/', '/students', Record<never, never>, Record<never, never>>,
    '/students/[id]': RouteRecordInfo<'/students/[id]', '/students/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
