name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - v2 # 建议指定只在 v2 分支上触发
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0

      - name: Create .env.local file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.EJ_BASE_URL }}" >> .env.local
          echo "VITE_APP_TITLE=${{ secrets.EJ_HEAD_TITLE }}" >> .env.local
          echo "VITE_FOOTER_TEXT=${{ secrets.EJ_FOOT_TITLE }}" >> .env.local

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist # <-- 这里已修改为您指定的分支
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy SEJ-F/${{github.sha}} From CI"
